using './main.bicep'

param prefix = 'secureinsure'
param environment = 'prod'
param location = 'eastus2'
param vnetAddressPrefix = '10.2.0.0/16'
param webSubnetPrefix = '10.2.1.0/24'
param appSubnetPrefix = '10.2.2.0/24'
param vmSize = 'Standard_B1ms'
param adminUsername = 'azureadmin'
param adminPassword = 'P@ssw0rd2024!DR'
